[package]
name = "albumconv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["cargo", "derive"] }
csv = "1.1"
deunicode = "1.3"
serde = { version = "1", features = ["derive"] }
